linters:
  enable:
    - gofmt
    - revive  # Replacing deprecated golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused

linters-settings:
  govet:
    enable-all: true
  revive:
    confidence: 0.8
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
        - errcheck
