linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint
        - errcheck
